experiment_name: "02_task2_static_energy"

model:
  ckpt_path: "maniskill_train_stack_cube_concat_goal_pos_big/ep1500-ba43500"

data:
  demos_path: "experiments_stack_cube/data/success_demos/success_demos.json"
  num_test_episodes: 30
  max_steps: 200
  num_actions_per_step: 32

guidance:
  type: "static"
  num_energy_centers: 2
  energy_scales: [-0.5, -0.5]
  sigma: 0.2
  max_guidance: null
  seed: 42
  enable_dynamic_energy_field: true

evaluation:
  metrics:
    - success_rate
    - average_jerk
    - min_obstacle_distance
  save_trajectories: true
  save_videos: true
  visualize: false

output_dir: "experiments_stack_cube/outputs/02_task2_static_energy"

save_actions: true
